files:
  - source: '*'
    ignore:
      - .github/
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE
      - '%two_letters_code%/'
    translation: '%original_path%/%original_file_name%'
