blank_issues_enabled: false
contact_links:
  - name: Hilfe über den "Discussions"-Tab
    url: https://github.com/TanjunBot/Tanjun-Dokumentation/discussions
    about: Hier findest du eine erste Anlaufstelle, um Fragen zu stellen und Probleme zu lösen.
  - name: Tanjun Discord Supportserver
    url: https://discord.arion2000.xyz/api/discord
    about: Auf unserem Discord Server kannst du Fragen stellen und dich mit anderen austauschen.
